### ISSUE TITLE
Style for mobile

### ISSUE THREAD

**Issue by AElmoznino** [believer/dashboard#7]
But maybe that's just a nice to have? Currently looks like this on Pixel 2:
<img width="352" alt="screen shot 2018-10-24 at 13 44 25" src="https://user-images.githubusercontent.com/16192907/47425448-fa56f500-d792-11e8-96f7-8d9e426cb7d9.png">

**Comment by believer** [comment]
@AElmoznino haha yeah I know 😅

**Comment by felix-hack** [comment]
I can take a look at it

**Comment by felix-hack** [comment]
When running `npm run dev` locally, I got the following error:
`Failed at the dashboard@0.15.0 dev script 'fpack serve -o bundle --development ./lib/es6/src/Index.bs.js'`.
Tested it on Windows 10 and Ubuntu 18.04.

**Comment by believer** [comment]
I'm probably going to rebuild this, will have this in mind.
