### ISSUE TITLE
Break down by date

### ISSUE THREAD

**Issue by AElmoznino** [believer/dashboard#8]
When there's a long list, it's currently hard to get a clear overview of when the PR/Trello-thingie happened. Would be nice to have it divided by date (for everything in the past week at least, but I dunno how long back it goes?), like so (ish):

```
<h3>Wednesday Oct 24</h3>
feat: yada yada
chore: yada again

<h3>Tuesday Oct 23</h3>
feat: something else
```
or something like that 😄

**Comment by believer** [comment]
Good idea, I've only had very short lists but seems totally valid to sort them by date!
